name : "Step 3"

on :
  workflow_dispatch:
  pull_request: 
    branches: 
      - main


jobs:
  new-job:
    permissions: write-all
    name: new job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16
      - run: npm ci
      - name: Run test
        run: npm test ./test/step3/step3.test.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Success Issue
        uses: ManojCSE17/open-issue@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Vous avez Réussi le Step 3
          body: Félicitation ! Vous avez réussi votre premier merge sur la branche main


        
    

 
  

