name : "Step 1"

on :
  workflow_dispatch:
  push: 
    branches: 
      - main


jobs:
  new-job:
    permissions: write-all
    name: new job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test of the code
        uses: xoviat/actions-pytest@0.1-alpha2
        with:
          args: 3 1
      - name: Create Sucess Issue
        uses: ManojCSE17/open-issue@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Vous avez Reuissi le Step 1
          body: Félicitation! vous avez reuissi votre premier push complet sur le repository


        
    

 
  

