name : "Step 1"

on :
  workflow_dispatch:
  push: 
    branches: 
      - main


jobs:
  new-job:
    permissions: write-all
    name: new job
    runs-on: ubuntu-latest
      # node-version:14.x

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run prettier
      - run: npm run linter
      - run: npm test
      - name: Create Success Issue
        uses: ManojCSE17/open-issue@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Vous avez Réussi le Step 1
          body: Félicitation ! Vous avez réussi votre premier push complet sur le repository


        
    

 
  

