name : "Step 1"

on :
  workflow_dispatch:
  push: 
    branches: 
      - main


jobs:
  new-job:
    permissions: write-all
    name: new job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test of the code
        uses: stefanoeb/jest-action@1.0.4
      - name: Create Success Issue
        uses: ManojCSE17/open-issue@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Vous avez Réussi le Step 1
          body: Félicitation ! Vous avez réussi votre premier push complet sur le repository


        
    

 
  

