name : "Step 1"

on :
  workflow_dispatch:
  push: 
    branches: 
      - main


jobs:
  new-job:
    permissions: write-all
    name: new job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16
      - run: npm ci
      - name: Run test
        uses: willcaul/jest-github-action@v2
        with:
          working-directory : "test/step1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Success Issue
        uses: ManojCSE17/open-issue@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Vous avez Réussi le Step 1
          body: Félicitation ! Vous avez réussi votre premier push complet sur le repository


        
    

 
  

